### ISSUE TITLE
Features to implement

### ISSUE THREAD

**Issue by Devessier** [42Taskmaster/taskmaster-web#4]
These are the features we have to implement:

- [x] Finish Configuration page
- [x] Finish One Program page
- [x] Create page to update the configuration of one program
- [x] Create page to create a program using a GUI instead of a YAML configuration file
- [x] Add buttons `Start all`/`Restart all` and `Stop all` to the Programs list page
- [x] Add a button in a Program page to delete it
- [x] Add a button to shutdown the taskmasterd
- [ ] ~~Implement dark mode~~
- [x] Implement French and English languages

**Comment by plcharriere** [comment]
Everything is done !
